The work is almost complete
Petiti146/java-filmorate pull request #2
Opened 2024-09-21 23:38 UTC by Petiti146

2024-09-21 23:48 UTC, Petiti146 commented
Привет, я уже часов 8 дорабатываю проект по этим тестам, и никаким образом не могу понять что не так, у меня сроки горят сильно, если чуть чуть укажешь на ошибки где я допустил их, я додумаю и исправлю, мне за 7 дней надо всю теорию 12 спринта пройти + проект сдать, а то вылетаю, спасибо за понимание

2024-09-22 19:09 UTC, z8q requested changes

2024-09-22 19:09 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    }
Можно поставить над классом аннотацию RequiredArgsConstructor,
будет создан конструктор для final non-initialised полей, то есть такой же (строки 25-28 можно будет убрать)

Инджект зависимостей будет происходить также как и с аннотацией Autowired

2024-09-22 19:09 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        int limit = count > 0 ? count : 10;
в контроллере есть проверка на отрицательное значение count
```JAVA
if (count <= 0) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Count must be a positive number");
}
```

2024-09-22 19:09 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            log.debug("Проверка доходит ли до этого места");
проверки в строках 64, 66, 68 можно убрать

2024-09-22 19:09 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        }
Логику проброса ошибок стоит перенести в сервисный слой, обработку для ResponseStatusException можно осуществить в ExceptionHandler при необходимости

На контроллере можно оставить только функционал приема запроса, валидации, отправки ответа

2024-09-22 19:09 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final FilmStorage filmStorage;
Можно привести архитектуру приложения к такому виду, при котором было бы четкое разграничение слоев и последовательное прохождение запроса по слоям:
слой контроллеров -> сервисы -> storage слой
То есть обращения из контроллера напрямую к storage нарушают последовательность и могут в дальнейшем приводить к усложнению понимания логики взаимодействия слоев

2024-09-22 19:09 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
>      }
Можно во всех классах применить аннотацию RequiredArgsConstructor над классом

2024-09-22 19:09 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    }
Можно добавить RequiredArgsConstructor над классом

Еще сервисные классы не содержат логики,
можно было бы нагрузить их, 
например в InMemoryUserStorage есть такой блок:
```JAVA
    public List<User> getCommonFriends(long userId, long otherUserId) {
        if (users.get(userId) == null || users.get(otherUserId) == null) {
            throw new NotFoundException("Пользователь или другой пользователь не найден");
        }

        User user = users.get(userId);
        User otherUser = users.get(otherUserId);

       // ...
    }
```
Мы могли бы перенести логику обработки пользователей в сервис, оставив на storage классе только логику сохранения и чтения данных. У нас storage уже есть метод getUser, который умеет бросать исключения,
то есть пользователей можно было бы запросить в сервисе таким образом
```JAVA
User user = userStorage.getUser(userId);
User otherUser = userStorage.getUser(otherUserId);
// ... дальнейшая обработка пользователей
```

И также с остальным кодом, если нет прямой связи с чтением или записью, то возможно стоит перенести в сервис

2024-09-22 19:09 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public void addLike(long filmId, long userId) {
Стоит добавить в интерфейс и поставить Override

2024-09-22 19:09 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (users.get(userId) == null || users.get(friendId) == null) {
Можно добавить проверку на добавление самого себя в друзья

2024-09-22 19:28 UTC, Petiti146 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final FilmStorage filmStorage;
Просто в тз указано что в filmservice должно быть только 3 метода - Создайте FilmService, который будет отвечать за операции с фильмами — добавление и удаление лайка, вывод 
10
10 наиболее популярных фильмов по количеству лайков. Пока пусть каждый пользователь может поставить лайк фильму только один раз.

2024-09-22 19:29 UTC, Petiti146 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final FilmStorage filmStorage;
Мне нужно добавить в filmservice метод по получению всех фильмов ?

2024-09-22 20:07 UTC, Petiti146 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public void addLike(long filmId, long userId) {
Я думаю что из за неправильной архитектуры кода, ты не понял что это метод FilmService, я думал сделать как ты просишь, но понял что логичнее просто реализацию этого метода поместить в FilmService, так как по тз этот метод должен быть там

2024-09-23 18:32 UTC, z8q approved these changes

2024-09-23 18:32 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public void deleteFilm(@PathVariable long filmId) { // все еще обращаюсь к filmStorage, я тебе направил в пачке сообщение
По сообщению могу предположить, что сами контроллеры из десятого спринта остаются, но логика переезжает в сервисы
```
Для FilmController:
- добавление фильма;
- обновление фильма;
- получение всех фильмов.
Для UserController:
- создание пользователя;
- обновление пользователя;
- получение списка всех пользователей.
```
в 11-м дополняется функционалом работы с лайками и друзьями
можно уточнить еще у наставника

Delete не обязателен, но применить можно)

2024-09-23 18:32 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final FilmStorage filmStorage;
к стораджам лучше обращаться через сервисы,
на случай, если будут возникать ошибки, то смотреть придется только в сервисах)
а так еще контроллер может вовлекаться в логику

2024-11-20 03:58 UTC, merged